// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASj4jELXNBTVkEZRHXcWHqk51EYzWE8FE',
    appId: '1:789594406769:web:d0b97976b0690c01b980d0',
    messagingSenderId: '789594406769',
    projectId: 'notification-86aff',
    authDomain: 'notification-86aff.firebaseapp.com',
    storageBucket: 'notification-86aff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBII3zN3LuQt-zDfcQkZBBLk102JEAKKrk',
    appId: '1:789594406769:android:0551730840452f71b980d0',
    messagingSenderId: '789594406769',
    projectId: 'notification-86aff',
    storageBucket: 'notification-86aff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9H0O-eXDOwh2phbfcvoGX5p3vCEVDWvE',
    appId: '1:789594406769:ios:6fba226bde5b5232b980d0',
    messagingSenderId: '789594406769',
    projectId: 'notification-86aff',
    storageBucket: 'notification-86aff.appspot.com',
    iosBundleId: 'com.example.roomiesFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9H0O-eXDOwh2phbfcvoGX5p3vCEVDWvE',
    appId: '1:789594406769:ios:6fba226bde5b5232b980d0',
    messagingSenderId: '789594406769',
    projectId: 'notification-86aff',
    storageBucket: 'notification-86aff.appspot.com',
    iosBundleId: 'com.example.roomiesFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASj4jELXNBTVkEZRHXcWHqk51EYzWE8FE',
    appId: '1:789594406769:web:31365d6ad5fb6255b980d0',
    messagingSenderId: '789594406769',
    projectId: 'notification-86aff',
    authDomain: 'notification-86aff.firebaseapp.com',
    storageBucket: 'notification-86aff.appspot.com',
  );
}
